### ISSUE TITLE
[ Pipenv install ] - Fail locally

### ISSUE THREAD

**Issue by Quentinchampenois** [cap-collectif/cap-collectif#9]
Hello, I have encountered a fail while installing locally your software

#### Description

After cloning repository, when running command `pipenv install`, installation fails because of `pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent` exception.

Reproducible with command `pipenv check`

#### Stacktrace
``` 
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/cli/command.py", line 515, in check
    do_check(
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/core.py", line 2835, in do_check
    p = plette.Pipfile.load(open(project.pipfile_location))
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 64, in load
    data = tomlkit.loads(content)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/api.py", line 41, in loads
    return parse(string)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/api.py", line 81, in parse
    return Parser(string).parse()
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/parser.py", line 154, in parse
    key, value = self._parse_table()
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/parser.py", line 993, in _parse_table
    table.raw_append(_key, item)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/items.py", line 1336, in raw_append
    self._value.append(key, _item)
  File "/opt/homebrew/lib/python3.8/site-packages/pipenv/vendor/tomlkit/container.py", line 265, in append
    raise KeyAlreadyPresent(key)
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "url " already exists.
```

#### Environment 

Python version : 3.8.16
MacOS : v13.0
pipenv : version 2023.2.18

#### Alternative solution

Comment line 1 and 2 in `Pipfile`

**Comment by spyl94** [comment]
It looks like a pipenv regression, but we reproduced the issue and [this commit](https://github.com/cap-collectif/cap-collectif/commit/09328103b85ebf4cb8c42e2fc95c7991490e2ecf) should fix this.

Feel free to reopen, if it's not the case !

**Comment by Quentinchampenois** [comment]
Thank you !
